# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Enable Gradle build cache for incremental builds
org.gradle.caching=true

# Enable parallel execution
org.gradle.parallel=true

# Enable configuration cache
org.gradle.configuration-cache=true

# AndroidX
android.useAndroidX=true

# Kotlin code style
kotlin.code.style=official

# Non-transitive R class
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=36
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
